env:
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo
    rclone_config: "ENCRYPTED[7cc3831730cbe761bcd082be3126bab2f5fb84f9a84d842f671e43425f16808e947c1c74c56695abce70eb5c9b75c86d]"
#task:
#   name: makeme
#   timeout_in: 120m
#      image: ubuntu:latest
#      cpu: 8
#      memory: 32G

task:
  name: Build
  skip: $CIRRUS_BRANCH == 'main'
  only_if: $CIRRUS_REPO_OWNER == 'Builder-rom'
  timeout_in: 4h
  persistent_worker:
    labels:
      name: AX61-1
    isolation:
      container:
        image: ubuntu:latest
        cpu: 24
        memory: 60G
        volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
    setupall_script:
      - chmod +x set
      - ./set
    download_background_script:
      - chmod +x download
      - ./download
    sync_script:
      - chmod +x sync
      - ./sync
    monitor_background_script:
      - chmod +x monitor
      - ./monitor
    make_script:
      - chmod +x make
      - ./make
    upload_script:
      - chmod +x ccache
      - ./ccache
    
