env:
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo
    rclone_config: "ENCRYPTED[8b18bed9d37bd79f1ff115acd10dc666434a40afe2718d54b7089a13fb693f0b1c05a5069d8d7ff1d2945cca533fedb4]"

task:
    name: makeme
    timeout_in: 120m
    container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G
    setupall:
      - apt update && DEBIAN_FRONTEND="noninteractive" TZ="America/New_York" apt-get install -y tzdata curl git sudo
      - bash <(curl https://raw.githubusercontent.com/Hellomaria9009/scripts/master/setup/android_build_env.sh)
    download_background_script: # To download ccache in background
      - ./download # Ccache download script
    sync_script: # To sync source
      - ./sync # Source sync script
    monitor_background_script: # To monitor ccache and machine status every minute, runs in background
      - ./monitor # Monitor script
    make_script: # Actual build script foreground
      - ./make # Build script to run
    upload_script: # Upload ccache to cloud foreground
      - ./ccache # Ccache uploading script
