env:
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo
    rclone_config: "ENCRYPTED[7cc3831730cbe761bcd082be3126bab2f5fb84f9a84d842f671e43425f16808e947c1c74c56695abce70eb5c9b75c86d]"

task:
    name: makeme
    timeout_in: 120m
    container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G
    download_background_script:
      - chmod +x download
      - ./download
    sync_script:
      - chmod +x sync
      - ./sync
    monitor_background_script:
      - chmod +x monitor
      - ./monitor
    make_script:
      - chmod +x make
      - ./make
    upload_script:
      - chmod +x ccache
      - ./ccache
    setupall_script:
      - chmod +x set
      - ./set
